"""
test_generate_claim_status.py

The 276 and 277 share a five-level hierarchy, one deeper than eligibility:
payer at 20, information receiver at 21, service provider at 19, subscriber at
22, and a dependent at 23 only where the patient is not the subscriber. The
tracked claim hangs off the subscriber or the dependent, never both, which is
the same trap the 837 and the eligibility pair carry.
"""

import random
from decimal import Decimal

import pytest

from x12sdk.generate import (
    ClaimStatusSpec,
    StatusPatientSpec,
    TrackedClaimSpec,
    generate_276,
    generate_277,
)
from x12sdk.io import X12ModelReader

from .support import assert_eq_model

GENERATORS = (("276", generate_276), ("277", generate_277))


def _read(text, tmp_path, name):
    path = tmp_path / name
    path.write_text(text)
    with X12ModelReader(str(path)) as reader:
        return list(reader.models())


def _segments(x12: str):
    return [
        segment.split("*")
        for segment in (s for s in x12.replace("\n", "").split("~") if s)
        if segment.split("*")[0] not in ("ISA", "GS", "GE", "IEA")
    ]


def _hl(x12: str, level_code: str):
    return [s for s in _segments(x12) if s[0] == "HL" and s[3] == level_code]


def _people(x12: str):
    return [s[3] for s in _segments(x12) if s[0] == "NM1" and s[1] in ("IL", "QC")]


# --- the output is real X12 -----------------------------------------------


@pytest.mark.parametrize("label,generate", GENERATORS)
@pytest.mark.parametrize("seed", [0, 1, 7, 42, 1234])
@pytest.mark.parametrize("patients", [1, 3, 10])
def test_generated_claim_status_parses(label, generate, seed, patients, tmp_path):
    """Every generated file must survive the parser and all its validators."""
    models = _read(generate(seed=seed, patients=patients), tmp_path, f"g.{label}")
    assert len(models) == 1
    provider = models[0].loop_2000a[0].loop_2000b[0].loop_2000c[0]
    assert len(provider.loop_2000d) == patients


@pytest.mark.parametrize("label,generate", GENERATORS)
@pytest.mark.parametrize("seed", [0, 3, 99])
def test_generated_claim_status_round_trips(label, generate, seed, tmp_path):
    """parse -> serialize must reproduce the generated bytes exactly."""
    path = tmp_path / f"generated-{seed}.{label}"
    path.write_text(generate(seed=seed, patients=5))
    assert_eq_model(str(path))


@pytest.mark.parametrize("label,generate", GENERATORS)
def test_segment_count_is_computed_not_guessed(label, generate):
    """SE01 must equal the segments from ST through SE; the model enforces it."""
    segments = _segments(generate(seed=11, patients=4))
    assert segments[-1][0] == "SE"
    assert int(segments[-1][1]) == len(segments)


@pytest.mark.parametrize(
    "label,generate,code", (("276", generate_276, "HR"), ("277", generate_277, "HN"))
)
def test_the_functional_group_identifies_the_transaction(label, generate, code):
    """GS01 is HR for an inquiry and HN for a response, derived from the model."""
    group = next(
        line
        for line in generate(seed=2, patients=2).splitlines()
        if line.startswith("GS*")
    )
    assert group.split("*")[1] == code


# --- the hierarchy ---------------------------------------------------------


@pytest.mark.parametrize("label,generate", GENERATORS)
def test_all_five_levels_are_present(label, generate):
    """Payer, information receiver, service provider, subscriber, dependent."""
    x12 = generate(seed=3, patients=20)
    for level in ("20", "21", "19", "22", "23"):
        assert _hl(x12, level), f"no HL at level {level}"


@pytest.mark.parametrize("label,generate", GENERATORS)
def test_hierarchical_ids_are_unique_and_point_at_a_real_parent(label, generate):
    """Every HL names an id not used before and a parent that already exists."""
    seen = set()
    for segment in (
        s for s in _segments(generate(seed=8, patients=12)) if s[0] == "HL"
    ):
        hl_id, parent, level = segment[1], segment[2], segment[3]
        assert hl_id not in seen, f"duplicate hierarchical id {hl_id}"
        if level == "20":
            assert parent == ""
        else:
            assert parent in seen, f"HL {hl_id} points at unknown parent {parent}"
        seen.add(hl_id)


@pytest.mark.parametrize("label,generate", GENERATORS)
def test_every_subscriber_is_parented_by_the_service_provider(label, generate):
    """Subscribers hang off the service provider, not off each other."""
    x12 = generate(seed=5, patients=6)
    provider = _hl(x12, "19")[0][1]
    subscribers = _hl(x12, "22")
    assert len(subscribers) == 6
    assert {s[2] for s in subscribers} == {provider}


@pytest.mark.parametrize("label,generate", GENERATORS)
def test_the_tracked_claim_hangs_off_whichever_level_is_the_patient(label, generate):
    """
    A TRN belongs to the subscriber when the subscriber is the patient and to
    the dependent otherwise, never to both. Counting them against the HL
    levels is what catches a builder that put them in the wrong place.
    """
    for rate, expected_level in ((0.0, "22"), (1.0, "23")):
        segments = _segments(generate(seed=6, patients=4, dependent_rate=rate))
        trn_count = sum(1 for s in segments if s[0] == "TRN")
        assert trn_count == 4
        x12 = generate(seed=6, patients=4, dependent_rate=rate)
        assert len(_hl(x12, expected_level)) == 4
        if expected_level == "22":
            assert not _hl(x12, "23")


@pytest.mark.parametrize("label,generate", GENERATORS)
def test_both_patient_branches_are_generated_by_default(label, generate):
    x12 = generate(seed=3, patients=20)
    assert _hl(x12, "22"), "no subscriber in the file"
    assert _hl(x12, "23"), "no dependent in the file"


# --- reproducibility -------------------------------------------------------


@pytest.mark.parametrize("label,generate", GENERATORS)
def test_the_same_seed_produces_the_same_bytes(label, generate):
    assert generate(seed=21, patients=6) == generate(seed=21, patients=6)


@pytest.mark.parametrize("label,generate", GENERATORS)
def test_different_seeds_produce_different_files(label, generate):
    assert generate(seed=21, patients=6) != generate(seed=22, patients=6)


@pytest.mark.parametrize("label,generate", GENERATORS)
def test_generation_does_not_disturb_the_global_random_state(label, generate):
    """A generator that seeded the global RNG would corrupt its caller's tests."""
    random.seed(4242)
    expected = [random.random() for _ in range(3)]
    random.seed(4242)
    generate(seed=1, patients=5)
    assert [random.random() for _ in range(3)] == expected


# --- the pair ---------------------------------------------------------------


def test_an_inquiry_and_its_response_describe_the_same_people():
    """
    The 276 renders demographics on a dependent and the 277 does not. Drawing
    those values for both keeps the two in step on one seed, so the pair is
    genuinely an inquiry and its answer rather than two unrelated files.
    """
    inquiry = generate_276(seed=9, patients=8, dependent_rate=0.5)
    response = generate_277(seed=9, patients=8, dependent_rate=0.5)
    assert _people(inquiry) == _people(response)
    assert len(_people(inquiry)) > 8, "fixture has no dependents"


def test_the_inquiry_states_the_charge_and_the_response_reports_on_it():
    spec = ClaimStatusSpec(
        patients=[
            StatusPatientSpec(
                claims=[
                    TrackedClaimSpec(
                        charge="1250.00",
                        paid="900.00",
                        patient_control_number="ACCT-7001",
                        status_category="F2",
                        status_code="65",
                    )
                ]
            )
        ]
    )
    inquiry = _segments(generate_276(seed=1, patients=spec))
    response = _segments(generate_277(seed=1, patients=spec))

    # the inquiry says what was billed and asks nothing else
    assert next(s for s in inquiry if s[0] == "AMT")[2] == "1250.00"
    assert not [s for s in inquiry if s[0] == "STC"]
    assert next(s for s in inquiry if s[0] == "TRN")[2] == "ACCT-7001"

    # the response carries the status and the amounts, and has no AMT
    stc = next(s for s in response if s[0] == "STC")
    assert stc[1] == "F2:65"
    assert stc[4] == "1250.00"
    assert stc[5] == "900.00"
    assert not [s for s in response if s[0] == "AMT"]


def test_the_trace_type_distinguishes_a_request_from_a_response():
    """TRN01 is 1 on a 276 and 2 on a 277."""
    assert (
        next(s for s in _segments(generate_276(seed=1, patients=1)) if s[0] == "TRN")[1]
        == "1"
    )
    assert (
        next(s for s in _segments(generate_277(seed=1, patients=1)) if s[0] == "TRN")[1]
        == "2"
    )


# --- scenario control ------------------------------------------------------


def test_a_payment_cannot_exceed_the_charge():
    with pytest.raises(ValueError, match="cannot exceed the charge"):
        TrackedClaimSpec(charge="100.00", paid="150.00")


def test_a_patient_without_claims_is_rejected():
    with pytest.raises(ValueError, match="at least one tracked claim"):
        StatusPatientSpec(claims=[])


def test_an_empty_specification_is_rejected():
    with pytest.raises(ValueError, match="at least one patient"):
        ClaimStatusSpec(patients=[])


def test_zero_patients_is_rejected():
    for generate in (generate_276, generate_277):
        with pytest.raises(ValueError, match="at least 1"):
            generate(seed=0, patients=0)


def test_amounts_stay_exact():
    """Decimal throughout, so a charge is not rounded through a float."""
    claim = TrackedClaimSpec(charge="0.07", paid="0.01")
    assert claim.charge == Decimal("0.07")
    assert isinstance(claim.paid, Decimal)
