"""
test_generate_eligibility.py

The 270 and 271 sit on the same four-level hierarchy, so they are tested
together: payer at level 20, provider at 21, subscriber at 22, and a dependent
at 23 only where the patient is not the subscriber.

Two defects this work exposed are pinned here. Neither could be reached by
parsing, which is why the corpus never caught them: one needs a loop built in
Python, the other needs a file with more than one subscriber, and no sample
has one.
"""

import random

import pytest

from x12sdk.generate import (
    BenefitSpec,
    EligibilitySpec,
    MemberSpec,
    generate_270,
    generate_271,
)
from x12sdk.io import X12ModelReader

from .support import assert_eq_model


def _read(text, tmp_path, name):
    path = tmp_path / name
    path.write_text(text)
    with X12ModelReader(str(path)) as reader:
        return list(reader.models())


def _segments(x12: str):
    """The transaction body, ST through SE, as ``[name, *fields]`` lists."""
    return [
        segment.split("*")
        for segment in (s for s in x12.replace("\n", "").split("~") if s)
        if segment.split("*")[0] not in ("ISA", "GS", "GE", "IEA")
    ]


def _hl(x12: str, level_code: str):
    return [s for s in _segments(x12) if s[0] == "HL" and s[3] == level_code]


GENERATORS = (("270", generate_270), ("271", generate_271))


# --- the output is real X12 -----------------------------------------------


@pytest.mark.parametrize("label,generate", GENERATORS)
@pytest.mark.parametrize("seed", [0, 1, 7, 42, 1234])
@pytest.mark.parametrize("members", [1, 3, 10])
def test_generated_eligibility_parses(label, generate, seed, members, tmp_path):
    """Every generated file must survive the parser and all its validators."""
    models = _read(generate(seed=seed, members=members), tmp_path, f"g.{label}")
    assert len(models) == 1
    receiver = models[0].loop_2000a[0].loop_2000b[0]
    assert len(receiver.loop_2000c) == members


@pytest.mark.parametrize("label,generate", GENERATORS)
@pytest.mark.parametrize("seed", [0, 3, 99])
def test_generated_eligibility_round_trips(label, generate, seed, tmp_path):
    """parse -> serialize must reproduce the generated bytes exactly."""
    path = tmp_path / f"generated-{seed}.{label}"
    path.write_text(generate(seed=seed, members=5))
    assert_eq_model(str(path))


@pytest.mark.parametrize("label,generate", GENERATORS)
def test_segment_count_is_computed_not_guessed(label, generate):
    """SE01 must equal the segments from ST through SE; the model enforces it."""
    segments = _segments(generate(seed=11, members=4))
    assert segments[-1][0] == "SE"
    assert int(segments[-1][1]) == len(segments)


@pytest.mark.parametrize(
    "label,generate,code", (("270", generate_270, "HS"), ("271", generate_271, "HB"))
)
def test_the_functional_group_identifies_the_transaction(label, generate, code):
    """GS01 is HS for an inquiry and HB for a response, derived from the model."""
    group = next(
        line
        for line in generate(seed=2, members=2).splitlines()
        if line.startswith("GS*")
    )
    assert group.split("*")[1] == code


# --- the hierarchy ---------------------------------------------------------


@pytest.mark.parametrize("label,generate", GENERATORS)
def test_both_member_branches_are_generated_by_default(label, generate):
    """
    A file with a useful number of members contains a member who is the
    subscriber and a member who is a dependent, so code that walks only one
    branch can be caught.
    """
    x12 = generate(seed=3, members=20)
    assert _hl(x12, "22"), "no subscriber in the file"
    assert _hl(x12, "23"), "no dependent in the file"


@pytest.mark.parametrize("label,generate", GENERATORS)
def test_hierarchical_ids_are_unique_and_point_at_a_real_parent(label, generate):
    """Every HL names an id not used before and a parent that already exists."""
    seen = set()
    for _, hl_id, parent, level, _child in (
        s for s in _segments(generate(seed=8, members=12)) if s[0] == "HL"
    ):
        assert hl_id not in seen, f"duplicate hierarchical id {hl_id}"
        if level == "20":
            assert parent == ""
        else:
            assert parent in seen, f"HL {hl_id} points at unknown parent {parent}"
        seen.add(hl_id)


@pytest.mark.parametrize("label,generate", GENERATORS)
def test_a_subscriber_declares_a_child_only_when_it_has_a_dependent(label, generate):
    """HL04 must be 1 exactly when another HL names this one as its parent."""
    segments = [s for s in _segments(generate(seed=4, members=12)) if s[0] == "HL"]
    parents = {s[2] for s in segments if s[2]}
    for _, hl_id, _parent, level, child in segments:
        if level in ("22", "23"):
            assert child == ("1" if hl_id in parents else "0")


@pytest.mark.parametrize("label,generate", GENERATORS)
def test_every_subscriber_is_parented_by_the_information_receiver(label, generate):
    """
    All subscribers hang off the receiver, not off each other. This is what
    the removed previous-HL rule got wrong.
    """
    x12 = generate(seed=5, members=6)
    receiver = _hl(x12, "21")[0][1]
    subscribers = _hl(x12, "22")
    assert len(subscribers) == 6
    assert {s[2] for s in subscribers} == {receiver}


# --- reproducibility -------------------------------------------------------


@pytest.mark.parametrize("label,generate", GENERATORS)
def test_the_same_seed_produces_the_same_bytes(label, generate):
    assert generate(seed=21, members=6) == generate(seed=21, members=6)


@pytest.mark.parametrize("label,generate", GENERATORS)
def test_different_seeds_produce_different_files(label, generate):
    assert generate(seed=21, members=6) != generate(seed=22, members=6)


@pytest.mark.parametrize("label,generate", GENERATORS)
def test_generation_does_not_disturb_the_global_random_state(label, generate):
    """A generator that seeded the global RNG would corrupt its caller's tests."""
    random.seed(4242)
    expected = [random.random() for _ in range(3)]
    random.seed(4242)
    generate(seed=1, members=5)
    assert [random.random() for _ in range(3)] == expected


# --- scenario control ------------------------------------------------------


def test_an_inquiry_and_its_response_can_share_one_specification():
    """
    The point of one spec type for both: a 270 and the 271 answering it are a
    matched pair, and a test fixture usually wants both.
    """
    spec = EligibilitySpec(
        members=[MemberSpec(benefits=(BenefitSpec(service_type="35"),))],
        payer_name="EXAMPLE HEALTH PLAN",
        provider_name="EXAMPLE MEDICAL GROUP",
    )
    inquiry = _segments(generate_270(seed=1, members=spec))
    response = _segments(generate_271(seed=1, members=spec))

    assert next(s for s in inquiry if s[0] == "EQ")[1] == "35"
    assert next(s for s in response if s[0] == "EB")[3] == "35"
    for segments in (inquiry, response):
        names = [s[3] for s in segments if s[0] == "NM1"]
        assert "EXAMPLE HEALTH PLAN" in names
        assert "EXAMPLE MEDICAL GROUP" in names


def test_a_271_carries_every_benefit_it_was_given():
    spec = EligibilitySpec(
        members=[
            MemberSpec(
                benefits=(
                    BenefitSpec(service_type="30"),
                    BenefitSpec(service_type="88", status="6"),
                    BenefitSpec(service_type="35"),
                )
            )
        ]
    )
    eb = [s for s in _segments(generate_271(seed=1, members=spec)) if s[0] == "EB"]
    assert [s[3] for s in eb] == ["30", "88", "35"]
    assert [s[1] for s in eb] == ["1", "6", "1"]


def test_a_270_refuses_more_than_one_benefit_rather_than_dropping_them():
    """
    Loop2100C.loop_2110c is a single loop on the 270, not a list as on the
    271, and the parser overwrites it on each EQ. Raising keeps the
    limitation visible instead of silently keeping only the last one.
    """
    spec = EligibilitySpec(
        members=[
            MemberSpec(
                benefits=(
                    BenefitSpec(service_type="30"),
                    BenefitSpec(service_type="35"),
                )
            )
        ]
    )
    with pytest.raises(ValueError, match="one EQ per member"):
        generate_270(seed=1, members=spec)


def test_zero_members_is_rejected():
    for generate in (generate_270, generate_271):
        with pytest.raises(ValueError, match="at least 1"):
            generate(seed=0, members=0)


def test_an_unknown_benefit_status_is_rejected():
    with pytest.raises(ValueError, match="status must be one of"):
        BenefitSpec(status="ZZ")


def test_an_empty_specification_is_rejected():
    with pytest.raises(ValueError, match="at least one member"):
        EligibilitySpec(members=[])


# --- regressions this work uncovered ---------------------------------------


@pytest.mark.parametrize("label,generate", GENERATORS)
def test_more_than_one_subscriber_per_receiver_is_representable(label, generate):
    """
    ``validate_hierarchy_ids`` required every HL to be parented by the
    *previous* HL in the file, which is not an X12 rule. It made a second
    subscriber impossible: it would have had to be parented by the first,
    while another check required the receiver. A provider checking
    eligibility for a list of patients is the ordinary use of a 270, and no
    sample in the corpus has more than one subscriber, so it never fired.
    """
    x12 = generate(seed=2, members=25)
    assert len(_hl(x12, "22")) == 25


def test_a_loop_with_no_ref_segments_validates():
    """
    ``_validate_duplicate_codes`` read ``ref_segment`` with a ``get()``
    default, but on a model built in Python the key is always present and set
    to None; only the parser pre-seeds a list. Every constructed loop that
    left REF out raised TypeError, on every transaction set that uses the
    check, not just these two.
    """
    from x12sdk.v5010.x12_271_005010X279A1.loops import Loop2100B
    from x12sdk.v5010.x12_271_005010X279A1.segments import Loop2100BNm1Segment

    loop = Loop2100B(
        nm1_segment=Loop2100BNm1Segment(
            entity_identifier_code="1P",
            entity_type_qualifier="2",
            name_last_or_organization_name="EXAMPLE MEDICAL GROUP",
            identification_code_qualifier="XX",
            identification_code="1234567893",
        )
    )
    assert loop.ref_segment is None
