"""
test_generate_837p.py

The same bar as the 835 generator: output must parse, satisfy every model
validator, round-trip byte for byte, and be reproducible from its seed.

The 837 adds a structural concern the 835 does not have. A patient is either
the subscriber or a dependent of one, and the two sit at different depths of
the HL hierarchy, so a generator that only ever emits one of them cannot be
used to test code that walks the other. These tests pin both branches down.
"""

from decimal import Decimal

import pytest

from x12sdk.generate import (
    ClaimSpec,
    PatientSpec,
    ServiceLineSpec,
    SubmissionSpec,
    build_837p,
    denial,
    generate_837p,
)
from x12sdk.io import X12ModelReader

from .support import assert_eq_model


def _read(x12: str):
    with X12ModelReader(x12) as reader:
        return list(reader.models())


def _segments(x12: str):
    """The transaction body, ST through SE, as ``[name, *fields]`` lists."""
    return [
        segment.split("*")
        for segment in (s for s in x12.replace("\n", "").split("~") if s)
        if segment.split("*")[0] not in ("ISA", "GS", "GE", "IEA")
    ]


def _claims(submission):
    """Every 2300 loop, from both the subscriber and the dependent branch."""
    found = []
    for loop_2000a in submission.loop_2000a:
        for loop_2000b in loop_2000a.loop_2000b:
            found.extend(loop_2000b.loop_2300 or [])
            for loop_2000c in loop_2000b.loop_2000c or []:
                found.extend(loop_2000c.loop_2300 or [])
    return found


# --- the output is real X12 -----------------------------------------------


@pytest.mark.parametrize("seed", [0, 1, 7, 42, 1234])
@pytest.mark.parametrize("claims", [1, 3, 10])
def test_generated_claims_parse(seed, claims):
    """Every generated file must survive the parser and all its validators."""
    models = _read(generate_837p(seed=seed, claims=claims))
    assert len(models) == 1
    assert len(_claims(models[0])) == claims


@pytest.mark.parametrize("seed", [0, 3, 99])
def test_generated_claims_round_trip(seed, tmp_path):
    """parse -> serialize must reproduce the generated bytes exactly."""
    path = tmp_path / f"generated-{seed}.837"
    path.write_text(generate_837p(seed=seed, claims=5))
    assert_eq_model(str(path))


def test_segment_count_is_computed_not_guessed():
    """SE01 must equal the segments from ST through SE; the model enforces it."""
    segments = _segments(generate_837p(seed=11, claims=4))
    assert segments[-1][0] == "SE"
    assert int(segments[-1][1]) == len(segments)


def test_the_functional_group_identifies_a_claim():
    """GS01 is HC for an 837, derived from the model, not from ST03."""
    x12 = generate_837p(seed=2, claims=2)
    group = next(line for line in x12.splitlines() if line.startswith("GS*"))
    assert group.split("*")[1] == "HC"


# --- the hierarchy ---------------------------------------------------------


def test_both_patient_branches_are_generated_by_default():
    """
    A file with a useful number of claims contains a patient who is the
    subscriber and a patient who is a dependent, so code that walks only one
    branch can be caught.
    """
    submission = _read(generate_837p(seed=3, claims=20))[0]
    loop_2000a = submission.loop_2000a[0]
    subscriber_claims = [
        claim
        for loop_2000b in loop_2000a.loop_2000b
        for claim in (loop_2000b.loop_2300 or [])
    ]
    dependent_claims = [
        claim
        for loop_2000b in loop_2000a.loop_2000b
        for loop_2000c in (loop_2000b.loop_2000c or [])
        for claim in (loop_2000c.loop_2300 or [])
    ]
    assert subscriber_claims, "no claim sits on the subscriber branch"
    assert dependent_claims, "no claim sits on the dependent branch"


def test_hierarchical_ids_are_unique_and_point_at_a_real_parent():
    """Every HL names an id not used before and a parent that already exists."""
    hl_segments = [
        s for s in _segments(generate_837p(seed=8, claims=12)) if s[0] == "HL"
    ]
    seen = set()
    for _, hl_id, parent, level, _child in hl_segments:
        assert hl_id not in seen, f"duplicate hierarchical id {hl_id}"
        if level == "20":
            assert parent == ""
        else:
            assert parent in seen, f"HL {hl_id} points at unknown parent {parent}"
        seen.add(hl_id)


def test_a_parent_declares_whether_it_has_children():
    """HL04 must be 1 exactly when another HL names this one as its parent."""
    hl_segments = [
        s for s in _segments(generate_837p(seed=4, claims=12)) if s[0] == "HL"
    ]
    parents = {s[2] for s in hl_segments if s[2]}
    for _, hl_id, _parent, _level, child in hl_segments:
        assert child == ("1" if hl_id in parents else "0")


def test_a_dependent_omits_the_subscriber_relationship_code():
    """
    SBR02 says the subscriber is the patient. On the dependent branch the
    patient is someone else, so it must be absent and PAT01 carries the
    relationship instead.
    """
    spec = SubmissionSpec(
        patients=[
            PatientSpec(
                claims=[
                    ClaimSpec(charge="100.00", lines=[ServiceLineSpec(charge="100.00")])
                ],
                dependent=True,
                relationship="19",
            )
        ]
    )
    segments = _segments(generate_837p(seed=1, claims=spec))
    sbr = next(s for s in segments if s[0] == "SBR")
    assert sbr[2] == ""
    pat = next(s for s in segments if s[0] == "PAT")
    assert pat[1] == "19"


def test_a_subscriber_patient_carries_relationship_18_and_no_pat():
    spec = SubmissionSpec(
        patients=[
            PatientSpec(
                claims=[
                    ClaimSpec(charge="100.00", lines=[ServiceLineSpec(charge="100.00")])
                ],
                dependent=False,
            )
        ]
    )
    segments = _segments(generate_837p(seed=1, claims=spec))
    sbr = next(s for s in segments if s[0] == "SBR")
    assert sbr[2] == "18"
    assert not [s for s in segments if s[0] == "PAT"]


# --- reproducibility -------------------------------------------------------


def test_the_same_seed_produces_the_same_bytes():
    assert generate_837p(seed=21, claims=6) == generate_837p(seed=21, claims=6)


def test_different_seeds_produce_different_files():
    assert generate_837p(seed=21, claims=6) != generate_837p(seed=22, claims=6)


def test_generation_does_not_disturb_the_global_random_state():
    """A generator that seeded the global RNG would corrupt its caller's tests."""
    import random

    random.seed(4242)
    expected = [random.random() for _ in range(3)]

    random.seed(4242)
    generate_837p(seed=1, claims=5)
    assert [random.random() for _ in range(3)] == expected


# --- scenario control ------------------------------------------------------


def test_a_specified_claim_appears_verbatim():
    spec = SubmissionSpec(
        patients=[
            PatientSpec(
                claims=[
                    ClaimSpec(
                        charge="450.00",
                        patient_control_number="ACCT-9001",
                        lines=[
                            ServiceLineSpec(charge="300.00", procedure="99214"),
                            ServiceLineSpec(
                                charge="150.00", procedure="85025", units=2
                            ),
                        ],
                    )
                ]
            )
        ],
        billing_provider_name="EXAMPLE MEDICAL GROUP",
        payer_name="EXAMPLE HEALTH PLAN",
    )
    segments = _segments(generate_837p(seed=5, claims=spec))

    clm = next(s for s in segments if s[0] == "CLM")
    assert clm[1] == "ACCT-9001"
    assert clm[2] == "450.00"

    sv1 = [s for s in segments if s[0] == "SV1"]
    assert [s[1] for s in sv1] == ["HC:99214", "HC:85025"]
    assert [s[2] for s in sv1] == ["300.00", "150.00"]
    assert [s[4] for s in sv1] == ["1", "2"]

    names = [s[3] for s in segments if s[0] == "NM1"]
    assert "EXAMPLE MEDICAL GROUP" in names
    assert "EXAMPLE HEALTH PLAN" in names


def test_the_claim_charge_equals_the_service_line_total():
    """CLM02 == SUM(SV102) is enforced by the model; the generator honours it."""
    segments = _segments(generate_837p(seed=17, claims=8))
    total = Decimal("0.00")
    claim_charge = None
    charges = []
    for segment in segments:
        if segment[0] == "CLM":
            if claim_charge is not None:
                charges.append((claim_charge, total))
            claim_charge, total = Decimal(segment[2]), Decimal("0.00")
        elif segment[0] == "SV1":
            total += Decimal(segment[2])
    charges.append((claim_charge, total))
    assert charges
    for charge, line_total in charges:
        assert charge == line_total


def test_claim_and_line_charges_must_agree():
    with pytest.raises(ValueError, match="must agree"):
        ClaimSpec(charge="100.00", lines=[ServiceLineSpec(charge="90.00")])


def test_adjustments_are_rejected_on_a_submission():
    """
    An 837 cannot say what a payer did not pay. Accepting an adjustment would
    drop it silently, so the specification refuses it.
    """
    with pytest.raises(ValueError, match="cannot be represented"):
        SubmissionSpec(
            patients=[
                PatientSpec(
                    claims=[
                        ClaimSpec(
                            charge="100.00",
                            lines=[
                                ServiceLineSpec(
                                    charge="100.00",
                                    adjustments=[denial("CO", "45", "20.00")],
                                )
                            ],
                        )
                    ]
                )
            ]
        )


def test_a_claim_without_service_lines_is_rejected():
    with pytest.raises(ValueError, match="at least one service line"):
        SubmissionSpec(patients=[PatientSpec(claims=[ClaimSpec(charge="100.00")])])


def test_a_patient_without_claims_is_rejected():
    with pytest.raises(ValueError, match="at least one claim"):
        PatientSpec(claims=[])


def test_a_submission_without_patients_is_rejected():
    with pytest.raises(ValueError, match="at least one patient"):
        SubmissionSpec(patients=[])


def test_an_unknown_dependent_relationship_is_rejected():
    with pytest.raises(ValueError, match="relationship must be one of"):
        PatientSpec(
            claims=[ClaimSpec(charge="10.00", lines=[ServiceLineSpec(charge="10.00")])],
            dependent=True,
            relationship="ZZ",
        )


def test_zero_claims_is_rejected():
    with pytest.raises(ValueError, match="at least 1"):
        generate_837p(seed=0, claims=0)


# --- regressions this work uncovered ---------------------------------------


def test_a_subscriber_can_be_built_without_naming_an_empty_ref_list():
    """
    ``Loop2010Ba.ref_segment`` declared ``min_length=0`` but had no default,
    which made it required: constructing a subscriber in Python meant passing
    ``ref_segment=[]`` by hand, and omitting it failed validation. The parser
    pre-seeds the list, so only callers building a model hit this.
    """
    spec = SubmissionSpec(
        patients=[
            PatientSpec(
                claims=[
                    ClaimSpec(charge="75.00", lines=[ServiceLineSpec(charge="75.00")])
                ]
            )
        ]
    )
    submission = build_837p(spec, seed=0)
    subscriber = submission.loop_2000a[0].loop_2000b[0].loop_2010ba
    assert subscriber.ref_segment == []
    assert "REF" not in submission.x12().split("NM1*IL")[1].split("NM1*PR")[0]
