"""
test_generate_834.py

The 834 is the one supported transaction with no HL hierarchy. A dependent is
not a loop nested under the subscriber but a separate member record, told
apart by INS01 and INS02. There is no branch to fall down, but the two kinds
of record still have to be generated, because code reading an 834 has to tell
them apart.

This file also pins the segment-count validator, which the 834 alone had
commented out.
"""

import random

import pytest

from x12sdk.generate import (
    CoverageSpec,
    EnrolleeSpec,
    EnrollmentSpec,
    generate_834,
)
from x12sdk.io import X12ModelReader

from .support import assert_eq_model


def _read(text, tmp_path, name="g.834"):
    path = tmp_path / name
    path.write_text(text)
    with X12ModelReader(str(path)) as reader:
        return list(reader.models())


def _segments(x12: str):
    return [
        segment.split("*")
        for segment in (s for s in x12.replace("\n", "").split("~") if s)
        if segment.split("*")[0] not in ("ISA", "GS", "GE", "IEA")
    ]


# --- the output is real X12 -----------------------------------------------


@pytest.mark.parametrize("seed", [0, 1, 7, 42, 1234])
@pytest.mark.parametrize("enrollees", [1, 3, 10])
def test_generated_enrollments_parse(seed, enrollees, tmp_path):
    """Every generated file must survive the parser and all its validators."""
    models = _read(generate_834(seed=seed, enrollees=enrollees), tmp_path)
    assert len(models) == 1
    assert len(models[0].loop_2000) == enrollees


@pytest.mark.parametrize("seed", [0, 3, 99])
def test_generated_enrollments_round_trip(seed, tmp_path):
    """parse -> serialize must reproduce the generated bytes exactly."""
    path = tmp_path / f"generated-{seed}.834"
    path.write_text(generate_834(seed=seed, enrollees=5))
    assert_eq_model(str(path))


def test_segment_count_is_computed_not_guessed():
    """SE01 must equal the segments from ST through SE."""
    segments = _segments(generate_834(seed=11, enrollees=4))
    assert segments[-1][0] == "SE"
    assert int(segments[-1][1]) == len(segments)


def test_the_functional_group_identifies_an_enrollment():
    """GS01 is BE for an 834, derived from the model."""
    group = next(
        line
        for line in generate_834(seed=2, enrollees=2).splitlines()
        if line.startswith("GS*")
    )
    assert group.split("*")[1] == "BE"


# --- the member records -----------------------------------------------------


def test_both_kinds_of_member_record_are_generated_by_default():
    """INS01 is Y for a subscriber and N for a dependent; both must appear."""
    segments = _segments(generate_834(seed=3, enrollees=20))
    indicators = {s[1] for s in segments if s[0] == "INS"}
    assert indicators == {"Y", "N"}


def test_a_subscriber_is_always_related_to_themselves():
    """
    INS02 is 18, self, whenever the record is the subscriber's own. A
    specification that says otherwise is corrected rather than honoured,
    because the combination is not meaningful.
    """
    enrollee = EnrolleeSpec(dependent=False, relationship="19")
    assert enrollee.relationship == "18"

    segments = _segments(
        generate_834(seed=1, enrollees=EnrollmentSpec(enrollees=[enrollee]))
    )
    ins = next(s for s in segments if s[0] == "INS")
    assert ins[1] == "Y"
    assert ins[2] == "18"


def test_a_dependent_keeps_the_relationship_it_was_given():
    enrollee = EnrolleeSpec(dependent=True, relationship="01")
    segments = _segments(
        generate_834(seed=1, enrollees=EnrollmentSpec(enrollees=[enrollee]))
    )
    ins = next(s for s in segments if s[0] == "INS")
    assert ins[1] == "N"
    assert ins[2] == "01"


def test_every_member_carries_the_same_group_number():
    """REF*1L is the group; one enrollment file covers one group."""
    segments = _segments(generate_834(seed=5, enrollees=8))
    groups = {s[2] for s in segments if s[0] == "REF" and s[1] == "1L"}
    assert len(groups) == 1


def test_each_member_gets_its_own_subscriber_number():
    """REF*0F identifies the member and must not repeat across the roster."""
    segments = _segments(generate_834(seed=5, enrollees=8))
    members = [s[2] for s in segments if s[0] == "REF" and s[1] == "0F"]
    assert len(members) == 8
    assert len(set(members)) == 8


# --- coverage ---------------------------------------------------------------


def test_every_specified_coverage_appears():
    spec = EnrollmentSpec(
        enrollees=[
            EnrolleeSpec(
                coverages=(
                    CoverageSpec(insurance_line="HLT"),
                    CoverageSpec(insurance_line="DEN"),
                    CoverageSpec(insurance_line="VIS", maintenance_type="024"),
                )
            )
        ],
        sponsor_name="EXAMPLE MEDICAL GROUP",
        payer_name="EXAMPLE HEALTH PLAN",
    )
    segments = _segments(generate_834(seed=1, enrollees=spec))
    hd = [s for s in segments if s[0] == "HD"]
    assert [s[3] for s in hd] == ["HLT", "DEN", "VIS"]
    assert [s[1] for s in hd] == ["021", "021", "024"]

    names = [s[2] for s in segments if s[0] == "N1"]
    assert "EXAMPLE MEDICAL GROUP" in names
    assert "EXAMPLE HEALTH PLAN" in names


def test_every_coverage_line_carries_a_begin_date():
    """HD without a DTP is not a valid coverage; the model requires it."""
    segments = _segments(generate_834(seed=6, enrollees=6))
    names = [s[0] for s in segments]
    for index, name in enumerate(names):
        if name == "HD":
            assert names[index + 1] == "DTP"


def test_a_member_with_no_coverage_specified_still_gets_one():
    assert EnrolleeSpec().coverages == (CoverageSpec(),)


# --- reproducibility -------------------------------------------------------


def test_the_same_seed_produces_the_same_bytes():
    assert generate_834(seed=21, enrollees=6) == generate_834(seed=21, enrollees=6)


def test_different_seeds_produce_different_files():
    assert generate_834(seed=21, enrollees=6) != generate_834(seed=22, enrollees=6)


def test_generation_does_not_disturb_the_global_random_state():
    """A generator that seeded the global RNG would corrupt its caller's tests."""
    random.seed(4242)
    expected = [random.random() for _ in range(3)]
    random.seed(4242)
    generate_834(seed=1, enrollees=5)
    assert [random.random() for _ in range(3)] == expected


def test_zero_enrollees_is_rejected():
    with pytest.raises(ValueError, match="at least 1"):
        generate_834(seed=0, enrollees=0)


def test_an_empty_specification_is_rejected():
    with pytest.raises(ValueError, match="at least one member"):
        EnrollmentSpec(enrollees=[])


# --- regressions this work uncovered ---------------------------------------


def test_a_wrong_segment_count_is_rejected(tmp_path):
    """
    validate_segment_count was commented out on the 834 alone, so it was the
    one transaction set that accepted a wrong SE01 in silence. All ten
    inherited samples already carried a correct count, so enabling it cost
    nothing and brought the 834 in line with the other seven.
    """
    text = generate_834(seed=1, enrollees=2)
    lines = text.splitlines()
    for index, line in enumerate(lines):
        if line.startswith("SE*"):
            fields = line.split("*")
            fields[1] = str(int(fields[1]) + 1)
            lines[index] = "*".join(fields)
            break
    path = tmp_path / "bad-count.834"
    path.write_text("\n".join(lines))

    with pytest.raises(Exception, match="(?i)segment count|se01|count"):
        with X12ModelReader(str(path)) as reader:
            list(reader.models())
