"""
test_generate.py

Generated files have to be indistinguishable from real ones as far as the
library is concerned: they must parse, satisfy every model validator including
the balance and segment-count rules, and round-trip byte for byte. They also
have to be reproducible, or they are useless as fixtures.
"""

from decimal import Decimal

import pytest

from x12sdk.generate import (
    ClaimSpec,
    RemittanceSpec,
    ServiceLineSpec,
    build_835,
    denial,
    generate_835,
    patient_responsibility,
    provider_adjustment,
)
from x12sdk.generate._values import ValueFactory, _luhn_check_digit
from x12sdk.io import X12ModelReader

from .support import assert_eq_model


def _read(x12: str):
    with X12ModelReader(x12) as reader:
        return list(reader.models())


# --- the output is real X12 -----------------------------------------------


@pytest.mark.parametrize("seed", [0, 1, 7, 42, 1234])
@pytest.mark.parametrize("claims", [1, 3, 10])
def test_generated_remittances_parse(seed, claims):
    """Every generated file must survive the parser and all its validators."""
    models = _read(generate_835(seed=seed, claims=claims))
    assert len(models) == 1
    remittance = models[0]
    total_claims = sum(len(loop.loop_2100) for loop in remittance.loop_2000)
    assert total_claims == claims


@pytest.mark.parametrize("seed", [0, 3, 99])
def test_generated_remittances_round_trip(seed, tmp_path):
    """parse -> serialize must reproduce the generated bytes exactly."""
    path = tmp_path / f"generated-{seed}.835"
    path.write_text(generate_835(seed=seed, claims=5))
    assert_eq_model(str(path))


def test_segment_count_is_computed_not_guessed():
    """SE01 must equal the segments from ST through SE; the model enforces it."""
    x12 = generate_835(seed=11, claims=4)
    body = [s for s in x12.replace("\n", "").split("~") if s]
    transaction = [s for s in body if s.split("*")[0] not in ("ISA", "GS", "GE", "IEA")]
    se_segment = next(s for s in transaction if s.startswith("SE*"))
    assert int(se_segment.split("*")[1]) == len(transaction)


# --- reproducibility -------------------------------------------------------


def test_the_same_seed_produces_the_same_bytes():
    assert generate_835(seed=5, claims=6) == generate_835(seed=5, claims=6)


def test_different_seeds_produce_different_files():
    assert generate_835(seed=5, claims=6) != generate_835(seed=6, claims=6)


def test_generation_does_not_disturb_the_global_random_state():
    """A generator that reseeds the global RNG would corrupt a caller's tests."""
    import random

    random.seed(1234)
    expected = [random.random() for _ in range(3)]

    random.seed(1234)
    generate_835(seed=99, claims=3)
    assert [random.random() for _ in range(3)] == expected


# --- scenario control ------------------------------------------------------


def test_a_specified_denial_appears_verbatim():
    """The point of scenarios: ask for a denial, get exactly that denial."""
    spec = [
        ClaimSpec(
            charge="500.00",
            lines=[
                ServiceLineSpec(
                    charge="500.00",
                    procedure="99213",
                    adjustments=[denial("CO", "97", "150.00")],
                )
            ],
        )
    ]
    x12 = generate_835(seed=1, claims=spec, payer_name="EXAMPLE HEALTH PLAN")

    assert "CAS*CO*97*150.00~" in x12
    assert "N1*PR*EXAMPLE HEALTH PLAN~" in x12
    assert "SVC*HC:99213*500.00*350.00" in x12, "line payment is derived"
    assert "CLP*PCN000001*1*500.00*350.00" in x12, "claim payment is derived"


def test_payment_is_derived_from_charge_and_adjustments():
    claim = ClaimSpec(
        charge="300.00",
        adjustments=[denial("CO", "45", "50.00")],
        lines=[
            ServiceLineSpec(
                charge="300.00", adjustments=[patient_responsibility("1", "25.00")]
            )
        ],
    )
    assert claim.adjustment_total == Decimal("75.00")
    assert claim.paid == Decimal("225.00")


def test_claim_and_line_charges_must_agree():
    with pytest.raises(ValueError, match="must agree"):
        ClaimSpec(charge="100.00", lines=[ServiceLineSpec(charge="90.00")])


def test_an_unknown_adjustment_group_is_rejected():
    with pytest.raises(ValueError, match="adjustment group"):
        denial("ZZ", "45", "10.00")


def test_zero_claims_is_rejected():
    with pytest.raises(ValueError, match="at least 1"):
        generate_835(seed=1, claims=0)


# --- values ----------------------------------------------------------------


def test_generated_npis_carry_a_valid_check_digit():
    """Downstream identifier validation should accept generated NPIs."""
    values = ValueFactory(3)
    for _ in range(20):
        npi = values.npi()
        assert len(npi) == 10 and npi.isdigit()
        assert npi[0] in "12"
        assert _luhn_check_digit(npi[:9]) == npi[9]


def test_split_amounts_sum_back_exactly():
    """Service line charges must total the claim charge, so the split is exact."""
    values = ValueFactory(8)
    for _ in range(50):
        total = values.amount(10, 5000)
        parts = values.rng.randint(1, 5)
        pieces = values.split(total, parts)
        assert len(pieces) == parts
        assert sum(pieces) == total


# --- regressions this work uncovered ---------------------------------------


def test_a_fully_paid_claim_with_no_adjustments_validates():
    """
    Loop2100.validate_balance read cas_segment with a get() default, but the
    key is always present as None on a model built in Python, so any claim
    without adjustments raised TypeError instead of validating.
    """
    spec = RemittanceSpec(claims=[ClaimSpec(charge="500.00")])
    transaction = build_835(spec, seed=1)
    claim = transaction.loop_2000[0].loop_2100[0]
    assert claim.cas_segment is None
    assert claim.clp_segment.claim_payment_amount == Decimal("500.00")


def test_the_balance_rule_still_rejects_an_unbalanced_claim():
    """The guard above must not have turned the validator off."""
    from x12sdk.v5010.segments import ClpSegment, Nm1Segment
    from x12sdk.v5010.x12_835_005010X221A1.loops import Loop2100

    with pytest.raises(ValueError, match="Unable to balance"):
        Loop2100(
            clp_segment=ClpSegment(
                patient_control_number="P1",
                claim_status_code="1",
                total_claim_charge_amount=Decimal("500.00"),
                claim_payment_amount=Decimal("400.00"),  # 100 short, no CAS
                claim_filing_indicator_code="CH",
            ),
            nm1_segment=[
                Nm1Segment(
                    entity_identifier_code="QC",
                    entity_type_qualifier="1",
                    name_last_or_organization_name="DOE",
                )
            ],
        )


def test_red_cross_reference_validation_actually_fires():
    """
    The 271 check read a field named ref_segments, which does not exist, so it
    silently passed on every transaction.
    """
    from x12sdk.v5010.segments import EbSegment
    from x12sdk.v5010.x12_271_005010X279A1.loops import Loop2110C
    from x12sdk.v5010.x12_271_005010X279A1.segments import Loop2110RefSegment

    def build(qualifier):
        return Loop2110C(
            eb_segment=EbSegment(eligibility_benefit_information="R"),
            ref_segment=[
                Loop2110RefSegment(
                    reference_identification_qualifier=qualifier,
                    reference_identification="X",
                )
            ],
        )

    with pytest.raises(ValueError, match="American Red Cross"):
        build("18")
    build("1W")  # an allowed qualifier is still accepted


# --- provider-level adjustments (PLB) --------------------------------------


def _segment(x12: str, name: str):
    return (
        next(s for s in x12.split("\n") if s.startswith(name + "*"))
        .rstrip("~")
        .split("*")
    )


def test_a_specified_provider_adjustment_appears_verbatim():
    spec = [ClaimSpec(charge="500.00", lines=[ServiceLineSpec(charge="500.00")])]
    x12 = generate_835(
        seed=1,
        claims=spec,
        provider_adjustments=[provider_adjustment("WO", "25.00", "PCN000099")],
    )
    plb = _segment(x12, "PLB")
    payee = next(s for s in x12.split("\n") if s.startswith("N1*PE*"))
    assert plb[1] == payee.rstrip("~").split("*")[4], "PLB01 names the payee"
    assert plb[3] == "WO:PCN000099", "reason and identifier form the composite"
    assert plb[4] == "25.00"
    assert _segment(x12, "BPR")[2] == "475.00", "BPR02 is claim payments less the PLB"


def test_a_negative_provider_adjustment_adds_to_the_check():
    x12 = generate_835(
        seed=1,
        claims=[ClaimSpec(charge="100.00")],
        provider_adjustments=[provider_adjustment("L6", "-1.50")],
    )
    assert _segment(x12, "PLB")[3:5] == ["L6", "-1.50"]
    assert _segment(x12, "BPR")[2] == "101.50"


def test_invented_claims_carry_one_adjustment_and_specified_claims_none():
    assert generate_835(seed=3, claims=4).count("\nPLB*") == 1
    assert "PLB*" not in generate_835(seed=3, claims=[ClaimSpec(charge="10.00")])
    assert "PLB*" not in generate_835(seed=3, claims=4, provider_adjustments=0)


def test_several_adjustments_share_one_plb_segment():
    x12 = generate_835(seed=3, claims=4, provider_adjustments=3)
    assert x12.count("\nPLB*") == 1
    assert len(_segment(x12, "PLB")) == 3 + 2 * 3, "id, date, then three pairs"


def test_the_plb_is_counted_in_se01():
    x12 = generate_835(seed=2, claims=3, provider_adjustments=2)
    body = [s for s in x12.replace("\n", "").split("~") if s]
    transaction = [s for s in body if s.split("*")[0] not in ("ISA", "GS", "GE", "IEA")]
    assert int(_segment(x12, "SE")[1]) == len(transaction)


def test_provider_adjustments_parse_back_and_round_trip(tmp_path):
    x12 = generate_835(seed=4, claims=3, provider_adjustments=2)
    plb = _read(x12)[0].footer.plb_segment
    assert plb is not None
    assert plb.adjustment_reason_code_2 is not None
    path = tmp_path / "plb.835"
    path.write_text(x12)
    assert_eq_model(str(path))


def test_invented_adjustments_never_drive_the_check_negative():
    for seed in range(25):
        x12 = generate_835(seed=seed, claims=2, provider_adjustments=6)
        assert Decimal(_segment(x12, "BPR")[2]) >= 0


def test_adjustments_exceeding_the_payment_cannot_be_specified():
    with pytest.raises(ValueError, match="cannot be negative"):
        RemittanceSpec(
            claims=[ClaimSpec(charge="10.00")],
            provider_adjustments=[provider_adjustment("WO", "11.00")],
        )


def test_more_than_six_provider_adjustments_are_rejected():
    with pytest.raises(ValueError, match="between 0 and 6"):
        generate_835(seed=1, claims=2, provider_adjustments=7)
    with pytest.raises(ValueError, match="at most six"):
        RemittanceSpec(
            claims=[ClaimSpec(charge="1000.00")],
            provider_adjustments=[provider_adjustment("L6", "-1.00")] * 7,
        )


def test_a_provider_adjustment_needs_a_reason():
    with pytest.raises(ValueError, match="reason code"):
        provider_adjustment("", "1.00")


# --- integration with denial analytics -------------------------------------


def test_denial_summary_matches_what_was_generated():
    """
    End-to-end: generation and analytics must agree. Skipped until the denials
    module lands (PR #9).
    """
    # an attribute check, not importorskip: a stale __pycache__ directory left
    # by another branch makes x12sdk.denials importable as an empty namespace
    # package, which would let this fail rather than skip
    try:
        from x12sdk.denials import denial_summary, iter_adjustments
    except ImportError:  # pragma: no cover - depends on the branch
        pytest.skip("x12sdk.denials is not present on this branch (PR #9)")

    spec = [
        ClaimSpec(
            charge="1000.00",
            lines=[
                ServiceLineSpec(
                    charge="1000.00", adjustments=[denial("CO", "97", "250.00")]
                )
            ],
        ),
        ClaimSpec(
            charge="600.00",
            lines=[
                ServiceLineSpec(
                    charge="600.00", adjustments=[denial("CO", "97", "150.00")]
                )
            ],
        ),
        ClaimSpec(
            charge="400.00",
            lines=[
                ServiceLineSpec(
                    charge="400.00",
                    adjustments=[patient_responsibility("1", "40.00")],
                )
            ],
        ),
    ]
    transaction = _read(generate_835(seed=2, claims=spec))[0]
    rows = denial_summary(list(iter_adjustments(transaction)))

    assert len(rows) == 1, "only the CO/97 bundling denials count"
    row = rows[0]
    assert (row.group_code, row.reason_code) == ("CO", "97")
    assert row.claim_count == 2
    assert row.total_amount == Decimal("400.00"), "250.00 + 150.00"
